-- AkiHQ optional Supabase schema
-- Run this in a new Supabase project's SQL editor.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.workspace_snapshots (
  user_id uuid primary key references auth.users(id) on delete cascade,
  workspace_id text not null,
  data jsonb not null check (jsonb_typeof(data) = 'object'),
  updated_at timestamptz not null default now()
);

comment on table public.workspace_snapshots is
  'One local-first AkiHQ workspace snapshot per authenticated user.';

alter table public.workspace_snapshots enable row level security;

-- Re-running the file should not duplicate policies.
drop policy if exists "Users can read their own AkiHQ snapshot" on public.workspace_snapshots;
drop policy if exists "Users can create their own AkiHQ snapshot" on public.workspace_snapshots;
drop policy if exists "Users can update their own AkiHQ snapshot" on public.workspace_snapshots;
drop policy if exists "Users can delete their own AkiHQ snapshot" on public.workspace_snapshots;

create policy "Users can read their own AkiHQ snapshot"
on public.workspace_snapshots
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create their own AkiHQ snapshot"
on public.workspace_snapshots
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own AkiHQ snapshot"
on public.workspace_snapshots
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own AkiHQ snapshot"
on public.workspace_snapshots
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists workspace_snapshots_updated_at_idx
  on public.workspace_snapshots (updated_at desc);

drop trigger if exists workspace_snapshots_set_updated_at on public.workspace_snapshots;
create trigger workspace_snapshots_set_updated_at
before update on public.workspace_snapshots
for each row execute function public.set_updated_at();

-- Provider webhook events are written by the optional Cloudflare Worker with
-- the service-role key. No browser/user policies are intentionally created.
create table if not exists public.integration_events (
  id bigint generated by default as identity primary key,
  workspace_id text not null default 'workspace_main',
  provider text not null,
  event_type text not null default 'unknown',
  external_event_id text,
  payload jsonb not null default '{}'::jsonb,
  request_meta jsonb not null default '{}'::jsonb,
  signature_verified boolean not null default false,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  processing_error text
);

alter table public.integration_events enable row level security;

create index if not exists integration_events_provider_received_idx
  on public.integration_events (provider, received_at desc);

create unique index if not exists integration_events_provider_external_unique
  on public.integration_events (provider, external_event_id)
  where external_event_id is not null;

-- Live Team Chat & Staff DM Sync
create table if not exists public.crm_team_messages (
  id text primary key,
  channel_id text not null,
  author_id uuid references auth.users(id) on delete cascade,
  author_name text not null,
  role text not null default 'Staff',
  text text not null,
  reactions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.crm_team_messages enable row level security;

drop policy if exists "Authenticated users can read team messages" on public.crm_team_messages;
drop policy if exists "Authenticated users can insert team messages" on public.crm_team_messages;

create policy "Authenticated users can read team messages"
on public.crm_team_messages for select
to authenticated using (true);

create policy "Authenticated users can insert team messages"
on public.crm_team_messages for insert
to authenticated with check (auth.uid() = author_id);

create index if not exists crm_team_messages_channel_created_idx
  on public.crm_team_messages (channel_id, created_at asc);

commit;
