import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
create domain geography as point;create domain geometry as point;
create function st_x(p geometry) returns float8 language sql immutable as 'select p[0]';
create function st_y(p geometry) returns float8 language sql immutable as 'select p[1]';
create function st_makepoint(x float8,y float8) returns geometry language sql immutable as 'select point(x,y)';
create function st_setsrid(p geometry,s integer) returns geometry language sql immutable as 'select p';
create function st_dwithin(p geography,q geography,d float8) returns boolean language sql immutable as 'select (p <-> q)*1000 <= d';
create function st_distance(p geography,q geography) returns float8 language sql immutable as 'select (p <-> q)*1000';
create table venues(id uuid primary key,slug text,name text,city_id uuid,address text,location geography,status text,accessibility jsonb);
create table feature_flags(key text primary key,enabled boolean,label_es text,label_en text);
create table crm_company_records(id text,workspace_id text,data jsonb,revision integer,publish_state text,publish_error text,seq bigint,deleted_at timestamptz,import_id uuid);
create table crm_catalogue_venues(workspace_id text,lead_id text,venue_id uuid);
create function crm_company_access() returns boolean language sql stable as $$select coalesce(current_setting('app.staff',true),'false')='true'$$;`);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260923000739_accommodation_vertical.sql',import.meta.url),'utf8'));
await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260923002500_accommodation_review_queue.sql',import.meta.url),'utf8'));
await db.exec(`insert into venues values ('10000000-0000-4000-8000-000000000001','hotel','Hotel Uno',null,'Madrid',point(-3.7,40.4),'published','{"claim_status":"unclaimed"}','accommodation','hotel'),('10000000-0000-4000-8000-000000000002','cafe','Casa Paco',null,'Madrid',point(-3.7,40.4),'published','{"claim_status":"unclaimed"}','activities',null);
insert into crm_company_records values ('a','ws_akipasa','{"name":"Hotel Uno"}',1,'published',null,1,null,null),('b','ws_akipasa','{"name":"Casa Paco"}',1,'published',null,2,null,null);
insert into crm_catalogue_venues values('ws_akipasa','a','10000000-0000-4000-8000-000000000001'),('ws_akipasa','b','10000000-0000-4000-8000-000000000002');`);
assert.equal((await db.query('select public_nearby_venue_page(40.4,-3.7,25) v')).rows[0].v.total,1);
const snap=(await db.query('select public_map_marker_snapshot_v2() v')).rows[0].v;
assert.equal(snap.count,2); assert.equal(snap.version,2);assert.equal(snap.markers[0][4],1);assert.equal(snap.markers[1][4],0);
await assert.rejects(db.query("select crm_company_list('','accommodation',0)"),/access denied/);
await db.exec("set app.staff='true'");
for (const type of ['activities','accommodation']) {const result=(await db.query('select crm_company_list(\'\',$1,0) v',[type])).rows[0].v;assert.equal(result.total,1);assert.equal(result.rows[0].discovery_vertical,type);}
assert.equal((await db.query("select enabled from feature_flags where key='akiduermo_public'")).rows[0].enabled,false);
await db.exec('set role anon');await assert.rejects(db.query('select * from akiduermo.accommodation_catalogue'),/permission denied/);
console.log('PASS: migration, paginated discovery exclusion, complete classified map, CRM category filters, permissions, dormant flag');
await db.close();
