import test from 'node:test';import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {parseAcknowledgement,sendRegistration,AEAT_ENDPOINTS} from './aeat-transport.js';
const info='https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroInformacion.xsd',ns='https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/RespuestaSuministro.xsd';
const expected={issuer_nif:'B12345674',document_number:'F2-2026-00000001',issue_date:'2026-09-25'};
export const response=(state='Correcto',extra='')=>`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:r="${ns}" xmlns:s="${info}"><soap:Body><r:RespuestaRegFactuSistemaFacturacion><r:CSV>1234567890ABCDEF</r:CSV><r:Cabecera><s:ObligadoEmision><s:NombreRazon>TEST ONLY Business</s:NombreRazon><s:NIF>${expected.issuer_nif}</s:NIF></s:ObligadoEmision></r:Cabecera><r:TiempoEsperaEnvio>60</r:TiempoEsperaEnvio><r:EstadoEnvio>${state==='AceptadoConErrores'?'ParcialmenteCorrecto':state}</r:EstadoEnvio><r:RespuestaLinea><r:IDFactura><s:IDEmisorFactura>${expected.issuer_nif}</s:IDEmisorFactura><s:NumSerieFactura>${expected.document_number}</s:NumSerieFactura><s:FechaExpedicionFactura>25-09-2026</s:FechaExpedicionFactura></r:IDFactura><r:Operacion><s:TipoOperacion>Alta</s:TipoOperacion></r:Operacion><r:EstadoRegistro>${state}</r:EstadoRegistro>${extra}</r:RespuestaLinea></r:RespuestaRegFactuSistemaFacturacion></soap:Body></soap:Envelope>`;
test('AEAT acknowledgement binds exact identity, retains CSV, raw evidence and throttle',()=>{const xml=response(),r=parseAcknowledgement(xml,expected);assert.equal(r.status,'accepted');assert.equal(r.csv,'1234567890ABCDEF');assert.equal(r.rawXml,xml);assert.equal(r.retryAfterSeconds,60);assert.throws(()=>parseAcknowledgement(xml,{...expected,document_number:'OTHER'}),/identity/);});
test('accepted-with-errors and duplicate records never become clean accepted status',()=>{assert.equal(parseAcknowledgement(response('AceptadoConErrores'),expected).status,'accepted_with_errors');assert.equal(parseAcknowledgement(response('Incorrecto','<r:RegistroDuplicado><s:IdPeticionRegistroDuplicado>TEST-ONLY-123</s:IdPeticionRegistroDuplicado><s:EstadoRegistroDuplicado>Correcta</s:EstadoRegistroDuplicado></r:RegistroDuplicado>'),expected).status,'duplicate_requires_reconciliation');});
test('malformed, oversized, XXE, spoofed namespace and missing verification code fail closed',()=>{
 for(const xml of ['<bad>',response().replace('xmlns:r="'+ns+'"','xmlns:r="https://evil.example/"'),response().replace('<r:CSV>1234567890ABCDEF</r:CSV>',''),'<!DOCTYPE x [<!ENTITY e SYSTEM "file:///etc/passwd">]>'+response(),'x'.repeat(1024*1024+1)])assert.throws(()=>parseAcknowledgement(xml,expected));
});
test('mTLS request uses only the pinned AEAT host, validates TLS, preserves response evidence',async()=>{
 let calls=0;
 const request=(url,opts,cb)=>{calls++;assert.equal(url,AEAT_ENDPOINTS.test);assert.equal(opts.rejectUnauthorized,true);assert.equal(opts.minVersion,'TLSv1.2');const req=new EventEmitter();req.setTimeout=()=>{};req.end=body=>{assert.match(body,/soapenv:Envelope/);const res=new EventEmitter();res.statusCode=200;cb(res);res.emit('data',Buffer.from(response()));res.emit('end');};return req;};
 const r=await sendRegistration({registration:{xml:'<sfLR:RegFactuSistemaFacturacion xmlns:sfLR="test"></sfLR:RegFactuSistemaFacturacion>',environment:'test'},environment:'test',expected,cert:'TEST CERT',key:'TEST KEY'},request);assert.equal(r.status,'accepted');assert.equal(calls,1);
 await assert.rejects(sendRegistration({registration:{environment:'test'},environment:'production',expected},request),/matching/);assert.equal(calls,1);
});
